### ISSUE TITLE
[FEAT] Realm 저장 알림 뷰 구현

### ISSUE THREAD

**Issue by rkdtnlzl** [Movielity/Movielity_iOS#21]
## 어떤 기능인가요?
Realm DB로 저장했을 때에 대한 알림 뷰 구현하겠습니다.

## 작업 상세 내용

- [x] 알림 팝업창 UI 구현
- [x] 팝업 창 Component화

**Comment by Acasiax** [comment]
구현 완료 했습니다 pull 받고 수정 작업해주시면 감사하겠습니다.
