### ISSUE TITLE
[FEAT] UI 세부 조정

### ISSUE THREAD

**Issue by MileyJump** [Movielity/Movielity_iOS#22]
## 어떤 기능인가요?
> 전체적인 화면의 세부적인 UI를 개선하여 수정하겠습니다!

## 작업 상세 내용

- [x] TabBar 백그라운드 색상 및 선택 시 컬러 변경
- [x] CustomButton의 Icon과 Title 간격 조정

**Comment by Acasiax** [comment]
이전에 구현하였던 메인뷰 -> 상세 미디어로 이동하는 코드 재완성 되면 메세지 부탁드립니다!
